title: <%= name %>
description: <%= description %>
baseurl: <%= baseurl %>
google-analytics: <%= ga %>

markdown: <%= md %>

exclude:
    - .tmp
    - dev
    - dist
    - node_modules
    - gulpfile.js
    - package.json
    - bower.json
    - bower_components
    - gulpfile.babel.js
    - README.md
    - editorconfig
    - scripts
